// <auto-generated />
namespace KolokviumskaDemek1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addISBN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addISBN));
        
        string IMigrationMetadata.Id
        {
            get { return "202406011239103_addISBN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
